// En @assets/menus/active/index.ts
export { default as BillSvg } from './bill.svg';
export { default as ChannelsSvg } from './Chanels.svg';
export { default as ClipSvg } from './Clip.svg';
export { default as DocSvg } from './Doc.svg';
export { default as GpsMarkerSvg } from './gps-marker.svg';
export { default as GraphicSvg } from './graphic.svg';
export { default as Home } from './Home.svg';
export { default as HubspotSvg } from './hubspot.svg';
export { default as IdiomaSvg } from './Idioma.svg';
export { default as ImageSvg } from './image.svg';
export { default as LockSvg } from './lock.svg';
export { default as MegaphonSvg } from './megaphon.svg';
export { default as PaymentSvg } from './Payment.svg';
export { default as PersonalinfoSvg } from './Personalinfo.svg';
export { default as PlanpagoSvg } from './planpago.svg';
export { default as ProductsSvg } from './Product.svg';
export { default as ProfileSvg } from './profile.svg';
export { default as ReportsSvg } from './Report.svg';
export { default as ShopSvg } from './shop.svg';
export { default as TagSvg } from './tag.svg';
export { default as TicketSvg } from './ticket.svg';
export { default as TrukSvg } from './truk.svg';
export { default as UrlSvg } from './url.svg';
export { default as paymenthSvg} from './paymenth.svg';
