// En @assets/menus/active/index.ts
export { default as BillSvg } from './bill.svg?react';
export { default as ChannelsSvg } from './Chanels.svg?react';
export { default as ClipSvg } from './Clip.svg?react';
export { default as DocSvg } from './Doc.svg?react';
export { default as GpsMarkerSvg } from './gps-marker.svg?react';
export { default as GraphicSvg } from './graphic.svg?react';
export { default as Home } from './Home.svg?react';
export { default as HubspotSvg } from './hubspot.svg?react';
export { default as IdiomaSvg } from './Idioma.svg?react';
export { default as ImageSvg } from './image.svg?react';
export { default as LockSvg } from './lock.svg?react';
export { default as MegaphonSvg } from './megaphon.svg?react';
export { default as PaymentSvg } from './Payment.svg?react';
export { default as PersonalinfoSvg } from './Personalinfo.svg?react';
export { default as PlanpagoSvg } from './planpago.svg?react';
export { default as ProductsSvg } from './Product.svg?react';
export { default as ProfileSvg } from './profile.svg?react';
export { default as ReportsSvg } from './Report.svg?react';
export { default as ShopSvg } from './shop.svg?react';
export { default as TagSvg } from './tag.svg?react';
export { default as TicketSvg } from './ticket.svg?react';
export { default as TrukSvg } from './truk.svg?react';
export { default as UrlSvg } from './url.svg?react';
export { default as paymenthSvg} from './paymenth.svg?react';
